<a href="https://colab.research.google.com/github/voshna123/C-/blob/main/Practice_tf_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [4]:
A = tf.constant([[1,23,89],
                [290,3121,1]])

A.shape, A.ndim, tf.size(A)

(TensorShape([2, 3]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [8]:
B = tf.constant(np.random.randint(0,2,size = 1500), shape = (5,300))
C = tf.constant(np.random.randint(0,2,size = 1500), shape = (5,300))
B.shape, C.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [9]:
tf.matmul(B, tf.transpose(C))

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [10]:
tf.tensordot(B, tf.transpose(C), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [15]:
B = tf.constant(np.random.uniform(low = 0, high = 1, size = (224,224,3)))
tf.reduce_min(B[:,]), tf.reduce_max(B[:])

(<tf.Tensor: shape=(), dtype=float64, numpy=1.6678107499501493e-06>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.9999868341755743>)

In [16]:
B = tf.constant(tf.constant(np.random.uniform(low = 0, high = 1, size = (224,224,3))), shape = (1,224,224,3))
tf.squeeze(B).shape

TensorShape([224, 224, 3])

In [21]:
C = tf.constant([1,2,3,4,5,6,7,8,100,101])
tf.argmax(C), tf.argmin(C)

(<tf.Tensor: shape=(), dtype=int64, numpy=9>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [20]:
tf.one_hot(C, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>