<a href="https://colab.research.google.com/github/voshna123/C-/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.17.1


In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
vector = tf.constant([[10,10],
                     [10,90]])

In [ ]:
vector.ndim

2

In [ ]:
vector2 = tf.constant([[10,10],
                     [10,90]], dtype = tf.float16)

## 2 tf.variable


In [5]:
changable = tf.Variable([10,7])
unchangable = tf.constant([10,7])

In [6]:
changable[0] = 20

TypeError: 'ResourceVariable' object does not support item assignment

In [7]:
changable[0].assign(80)
changable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([80,  7], dtype=int32)>

In [8]:
unchangable[0].assign(80)
unchangable

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating Random Tensors

In [11]:
rand = tf.random.Generator.from_seed(42)
rand = rand.normal(shape = (3,5))
rand

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
       [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
       [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ]],
      dtype=float32)>

## Shuffling order of elements in tensor

In [12]:
not_shuffled = tf.constant([[10,7],
                            [1,9],
                            [890,8121]])

In [13]:
shuffled = tf.random.shuffle(not_shuffled, seed =42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 890, 8121],
       [   1,    9],
       [  10,    7]], dtype=int32)>

## Setting global seed

In [14]:
tf.random.set_seed(42)

In [15]:
tf.ones([10,2,3])

<tf.Tensor: shape=(10, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [17]:
tf.zeros([10,9])

<tf.Tensor: shape=(10, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Convert numpy array into tf tensor

In [19]:
import numpy as np

numpy_A = np.arange(1,25, dtype = np.int32)

A = tf.constant(numpy_A, shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [22]:
tf4 = tf.zeros([2,2,2,2])
tf4, tf.size(tf4), tf4.shape, tf4.ndim

(<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
 array([[[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]],
 
 
        [[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=16>,
 TensorShape([2, 2, 2, 2]),
 4)

## Indexing Tensors

In [25]:
tf4[0:2,0:2,0:2,0:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
tf4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[0., 0.]]]], dtype=float32)>

In [30]:
tf2 = tf.constant([[10,7],
                   [12,45]])

tf2[-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 45], dtype=int32)>

## Add new dimension

In [31]:
tf3 = tf2[..., tf.newaxis]
tf3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[12],
        [45]]], dtype=int32)>

In [33]:
tf.expand_dims(tf2, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[12],
        [45]]], dtype=int32)>

## Manipulating Tensors

+
-
*
/

In [40]:
tf1 = tf.constant([[10,7]
                   ,[3,4]])

tf1+10, tf1-10, tf.math.multiply(tf1,2), tf.math.divide(tf1,2)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 14],
        [ 6,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[5. , 3.5],
        [1.5, 2. ]])>)

## Matrix Multiplication



*   tf.matmul()
*   tf.tensordot()



In [41]:
tf.matmul(tf1, tf1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
X = tf.constant([[1,2],
                 [23,67],
                 [21,90]])

X1 = tf.constant([[23,56],
                  [67,921]])

tf.matmul(X, X1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  157,  1898],
       [ 5018, 62995],
       [ 6513, 84066]], dtype=int32)>

In [46]:
X = tf.constant([[1,2],
                 [23,67],
                 [21,90]])

X1 = tf.constant([[23,56],
                  [67,921],
                  [91,69]])



X1 = tf.reshape(X1, shape = (2,3))

tf.matmul(X, X1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1865,   238,   205],
       [62236,  7385,  6164],
       [83373,  9366,  7617]], dtype=int32)>

In [50]:
X = tf.constant([[1,2],
                 [23,67],
                 [21,90]])

X1 = tf.constant([[23,56],
                  [67,921],
                  [91,69]])



X1 = tf.transpose(X1)

tf.matmul(X, X1), tf.tensordot(X, X1, axes = 1)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  135,  1909,   229],
        [ 4281, 63248,  6716],
        [ 5523, 84297,  8121]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  135,  1909,   229],
        [ 4281, 63248,  6716],
        [ 5523, 84297,  8121]], dtype=int32)>)

## Changing tensor dtype

In [51]:
B = tf.constant([1.9,2.3])
C = tf.constant([1,2])

B.dtype, C.dtype

(tf.float32, tf.int32)

In [52]:
D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.9, 2.3], dtype=float16)>

## Aggregrating Tensors

*   max
*   min
*   sum
*   mean





In [53]:
D = tf.constant([10,34])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 34], dtype=int32)>

In [56]:
E = tf.constant(np.random.randint(0,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([37, 78, 60,  7, 91, 66, 96, 78, 30, 87, 35, 26, 27, 97, 13, 91, 55,
       57, 12, 13, 38, 20, 79, 11, 10, 59, 58, 34, 45, 46, 47, 74, 32, 80,
       20, 15, 28, 29, 33,  4, 29, 99, 50, 97, 98, 59, 60, 74, 73, 54])>

In [61]:
tf.reduce_min(E).numpy(), tf.reduce_max(E).numpy(), tf.reduce_mean(E).numpy(), tf.reduce_sum(E).numpy(), tf.math.reduce_variance(tf.cast(E, dtype = tf.float32)).numpy(), tf.math.reduce_std(tf.cast(E, dtype = tf.float32)).numpy()

(4, 99, 50, 2511, 807.0115, 28.407948)

## Find index of maximum, minimum

In [64]:
tf.argmax(E), tf.argmin(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=41>,
 <tf.Tensor: shape=(), dtype=int64, numpy=39>)

## Squeezing tensors

In [66]:
F = tf.constant([[[[12,34]]]])
F

<tf.Tensor: shape=(1, 1, 1, 2), dtype=int32, numpy=array([[[[12, 34]]]], dtype=int32)>

In [67]:
tf.squeeze(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 34], dtype=int32)>

## one hot encoding

In [69]:
l1 = [0,1,2,3]

tf.one_hot(l1, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [70]:
tf.one_hot(l1, depth = 4, on_value = "yes", off_value = "NO")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'NO', b'NO', b'NO'],
       [b'NO', b'yes', b'NO', b'NO'],
       [b'NO', b'NO', b'yes', b'NO'],
       [b'NO', b'NO', b'NO', b'yes']], dtype=object)>

## Math stuff

In [71]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [72]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [73]:
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [74]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## GPUs

In [75]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]